### PR TITLE
bus.unref() added in GstAudioFile

### PR DESCRIPTION
**Pull request by khlukekim**
see issue #28

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks for opening the PR!

I'm having trouble figuring out if this is the right fix. To test it, I made a modified version of the included `decode.py` that puts the invocation in a loop:

```py
if __name__ == '__main__':
    for i in range(100):
        print(i)
        decode(sys.argv[1])
```

and ran it on (a) a file that GStreamer *can* decode, and (b) a file that it *cannot* decode, so audioread falls back to FFmpeg.

In the gst-failed case (b), I reproduced a hang after just a few invocations. The hang happened in the `pipeline.set_state(Gst.State.NULL)` call in the `close` method. Even after applying your fix, though, the hang still happened—seemingly in the same place.

I also tried another approach (which you can see I committed and then reverted), but it also didn't work.

Do you have a way of reproducing the crash you're seeing? Does it seem to be fixed by this patch?

Sometimes, I really hate working with the GStreamer API—there are so many vague, undocumented corners that it seems impossible to do anything right without guessing and checking…

**Comment by khlukekim** [comment]
Sorry, I omitted too much details.

Actually the crash I've had was somewhat different.
My colleague was trying to decode about 3000 .mp3 files that Gstreamer cannot decode using librosa, in Ubuntu 14.04. The crash happened inside the _ca_available() of the 504th file, while opening a pipe to list available libraries. At this moment, it produced "too many open files" error. Changing ulimit did not help at this moment.

So I copied one of the files to my server, and wrote a simple code as follow
```
for i in range(1000):
    audioread.audio_open("sample.mp3")
```
This code crashed at the exact same moment - the 504th loop. But it produced cannot decode error. 

After some research, I found that commenting out the Gstreamer part solves the problem. And then found more specific solution, which is the PR.

**Comment by sampsyo** [comment]
Aha! Thanks for the extra information. Is there any chance you're in a position to share an MP3 file that triggers the leak?

**Comment by khlukekim** [comment]
Well I sent one via your personal e-mail, it's from CAL500 expansion dataset.

**Comment by sampsyo** [comment]
Awesome; thank you. This did let me produce the problem, exactly as you wrote: it crashed with an out-of-FDs error after 505 (in my case) opens.

And applying your patch actually does suppress the problem—but only when I run under Python 2! When I run the same test on Python 3.5.1 (with the same PyGI bindings, version 3.18.2, on the same machine), it introduces a bunch of reference-counting errors (dereferencing an object with ref-count zero).

So I tried removing the `unref` call in your patch, in the hope that the PyGI bindings are smart enough to take care of reference counting for us. This way, the only new thing is the call to `remove_signal_watch`. In an utterly ludicrous turn of events, *this fixes the crash under Python 3 but not Python 2*. :imp: :fire: :angry: :boom: 

My conclusion is that there are two issues here:
* One about reference counting, which is Python 2 specific, and a naive fix breaks on Python 3.
* The missing [`remove_signal_watch`](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstBus.html#gst-bus-remove-signal-watch), which is required to balance our call to [`add_signal_watch`](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstBus.html#gst-bus-add-signal-watch).

I'm committing the latter now and will keep looking into the former.

**Comment by sampsyo** [comment]
OK! I've found, experimentally, that a `del self.pipeline` is enough to make this work on both Pythons. Can you check whether this works for you too?

**Comment by khlukekim** [comment]
Removing bus things and putting ```del self.pipeline``` after the last line of ```close()``` did not work for me. It raises ```NoBackendError``` at 506th trial. 

By the way, after running a script calling ```audio_open()``` my terminal don't echo my input even it is called just once. May this be related with the current problem?

**Comment by sampsyo** [comment]
> Removing bus things and putting del self.pipeline after the last line of close() did not work for me. It raises NoBackendError at 506th trial.

Strange! Did you try pulling the entirety of the latest source, which also includes the `remove_signal_watch` call?

> By the way, after running a script calling audio_open() my terminal don't echo my input even it is called just once. May this be related with the current problem?

Weird; just invoking GStreamer is messing up your terminal? I haven't run into that…

**Comment by khlukekim** [comment]
Well, I put back the ```remove_signal_watch()``` call, and it worked magically! Thanks, now I'll get all the servers updated!

**Comment by sampsyo** [comment]
Great! I'll put a new release out on PyPI.

**Pull request closed without merging**
