### PR TITLE
Add a simple testsuite

### PR DESCRIPTION
**Pull request by ssssam**
I wrote a simple testsuite using py.test while investigating https://github.com/beetbox/audioread/pull/78.

Currently it only tests the audioread.audio_open() method. I'd like to add a separate set of tests for each backend, as I think there are some bugs in both the GStreamer and libmad backends that are causing everything to end up being run through ffmpeg. I don't know if I'll get time for that though.

### CODE REVIEW

**Comment by ssssam** [comment]
Now I spot that https://github.com/beetbox/audioread/pull/73/ also contains a test suite, which looks more comprehensive than this one.

**Comment by sampsyo** [comment]
Awesome! These tests look great already—but you're right; it looks like we let that other PR languish. I don't see any outstanding issues with that PR, so maybe we should merge that one and try to unify the two test suites.

**Comment by sampsyo** [comment]
Got it. Thanks for investigating. Let's forge ahead with merging a test suite and worry about seeking separately.

I think starting with files on disk (instead of generating them) seems simplest, especially if we can keep the files small! Let's do that.

As for unittest vs. py.test: I typically opt for the built-in stdlib module, which makes it easy to run the tests without any dependencies using any old test runner (e.g., nose), but I don't have any objection to py.test if that's what you're more familiar with. One thing that would be great to steal form #79 is the [tox](https://tox.readthedocs.io/en/latest/) configuration, which makes it easy to run the tests without worrying about dependencies (and across different Python versions).

**Comment by ssssam** [comment]
I happen to prefer py.test, I find the test code a lot easier to read. If you're happy with that then let's go with this branch for a tes suite. I've added a Tox configuration; I have left the Travis CI config running pytest directly because it seems to already manage multiple versions of Python.

**Comment by sampsyo** [comment]
Looks great; thanks!! I'll merge this now.

**Pull request merged**
